# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'revenueAndExpance' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Charts'
  # Pods for revenueAndExpance

  target 'revenueAndExpanceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'revenueAndExpanceUITests' do
    # Pods for testing
  end

end
